### PR TITLE
Added the ability to download packages and OpenBSD binaries automatically and add them to the image file

### PR DESCRIPTION
**Pull request by xoro**
# Changes

* Added several command line parameters.
* Added a default value for each command line parameter.
* Changed the README to the new abilities of resflash.
* The changes were tested with OpenBSD 5.7 amd64.

# TODO
* Testing other OpenBSD versions with other architectures.
* Adding a SHA256 test of the downloaded packages and OpenBSD binaries.

### CODE REVIEW

**Comment by bconway** [comment]
Interesting. Thanks for contributing.

Please take a look again at the two Features sections of the README. These are both features and directions of the project. It is important that resflash be branch- and arch-agnostic. It needs to support two releases, -current, and releases between the time CVS is marked as _BRANCH and the actual release date (such as 5.8 now). At lot of your package code won't work in all those situations. Many of the things you're trying to attempt here I think should be left as scripted by the user (perhaps I'll clean up my resflash-tools repo for publishing as examples).

Things like a simple build command are something I want to keep, compared to adding a dozen knobs with a dozen defaults. Base_dir and img_size should be required from a user and not defaulted away, so they know what they're about the build. Suddenly unpacking hundreds of MB of data into the current working directory(s) without a warning is a *bad* idea.

Also, your setting of a default for the com0 speed will always force a com0 console, with no option for a VGA console.

I'll skim it again and see if there are other things worth picking. Thanks.

**Comment by xoro** [comment]
First I'd like to thank you for resflash.
I simply create a separate script that calls the build_resflash.sh script using the specific command line arguments.
Thanks again.

**Comment by xoro** [comment]
I will close the pull request because I created a wrapper script (https://github.com/xoro/tlaloc) that uses resflash to create the OpenBSD images.

**Comment by xoro** [comment]
Just a simple question: would it be possible that you also tag your resflash git repository so that I can use the TAG to checkout a specific resflash verison in my tlaloc script? This would make it easier than using the sha checksum of the commit. The purpose of the tlaloc script is to make it easy for CI tests to always run the exact same binary OpenBSD images that are created using resflash/tlaloc before every test run.

**Comment by bconway** [comment]
Done!

**Comment by xoro** [comment]
Thanks, really cool!!!!
Just a little thing to mention: To skip the fw_update you use the -h flag in the README.md and the -n flag in the build_resflash.sh.
Tanks again.

**Comment by bconway** [comment]
Intentional, thanks. ;) Param -h is for help, and skipping fw_update is intended to be undocumented unless people read the source.

**Comment by bconway** [comment]
Just a heads up, I just committed v5.8.6 with support for remote package installation at build time, with a minimum of knobs and still remaining branch- and arch-agnostic. Hopefully it will be of use to you:

https://github.com/bconway/resflash/commit/cc1ecfc3ee99dbcadf5e978de85002074d4ea566

**Comment by cactus** [comment]
:+1:

**Pull request closed without merging**
